    <footer id="footer">
        <nav class="container">
            <div class="row">
                <div class="span3">
                    <h3>Что будет?</h3>
                    <p><a href="/schedle/">Программа конференции</a></p>
                </div>
                <div class="span3">
                    <h3>Кто пойдёт?</h3>
                    <ul>
                        <li><a href="/speakers/">Докладчики</a></li>
                        <li><a href="/people/">Участники</a></li>
                    </ul>
                </div>
                <div class="span3">
                    <h3>Где и когда?</h3>
                    <p>19 мая 2012,
                    <br />Санкт-Петербург, ИТМО</p>
                    <p><a href="/map/">Схема проезда</a></p>
                </div>
                <div class="span3">
                    <h3>Контакты</h3>
                    <p>Email: <a href="mailto:contact@ux-spb.ru">contact@ux-spb.ru</a><br />
                    Телефон: <a href="callto:+78123369344">+7 (812) 336 93 44</a></p>
                </div>
            </div>

            <div id="social">
                <ul class="clearfix">
                    <li class="facebook"><a class="ico hide-text" href="#">Facebook</a></li>
                    <li class="twitter"><a class="ico hide-text" href="#">Twitter</a></li>
                    <li class="linkedin"><a class="ico hide-text" href="#">LinkedIn</a></li>
                    <li class="flickr"><a class="ico hide-text" href="#">Flickr</a></li>
                    <li class="vimeo"><a class="ico hide-text" href="#">Vimeo</a></li>
                    <li class="email"><a class="ico hide-text" href="#">Email</a></li>
                </ul>
            </div>
        </nav>
    </footer>

    <script src="{{ STATIC_URL }}js/jquery.js"></script>
    <script src="{{ STATIC_URL }}js/less.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.js"></script>
</body>
</html>