    <header id="header">
        <div class="container">
            <hgroup id="branding">
                <div class="offset4">
                    <h1 id="site-title" class="visible-desktop"><a class="hide-text" href="/">ПрофсоUX</a></h1>
                    <h2 id="site-description">Конференция по юзабилити<br />и проектированию взаимодействия</h2>
                    <p><time>19 мая 2012</time>, Санкт-Петербург, ИТМО</p>
                </div>
            </hgroup>
        </div>
    </header>