<header id="header">
        <div class="container">
            <div id="branding" class="row">
                <div id="logo" class="span3 offset2 clearfix">
                    <a  href="/"><img src="{{ STATIC_URL }}img/branding/logo.png" alt="" /></a>
                </div>
                
                <hgroup class="span6">
                    <h1><a href="/">ПрофсоUX</a></h1>
                    <h2>Конференция UX-специалистов</h2>
                    <p><time>19 мая 2012</time>, Санкт-Петербург, ИТМО</p>
                </hgroup>
            </div>
        </div>
    </header>