<!DOCTYPE HTML>
<html lang="ru-RU">
<head>
    <meta charset="utf-8">
    <title>ПрофсоUX – Первая UX-конференция в Санкт-Петербурге</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- <link href="{{ STATIC_URL }}less/style.less" rel="stylesheet/less"> -->
    <link href="{{ STATIC_URL }}css/style.css" rel="stylesheet">
    
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link href="{{ STATIC_URL }}favicon.ico" rel="shortcut icon" type="image/x-icon">
</head>