<nav id="nav-main" class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <div class="nav-collapse">
                <ul class="nav">
                    <li><a href="/schedule/">Программа</a></li>
                    <li><a href="/speakers/">Докладчики</a></li>
                    <li><a href="/people/">Кто пойдёт?</a></li>
                    <li><a href="/map/">Место проведения</a></li>
                    <li><a href="/contacts/">Контакты</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</nav>