<div id="share-block">
	<h3>Рассказать друзьям</h3>

	<script type="text/javascript">(function() {
	 if (window.pluso)if (typeof window.pluso.start == "function") return;
	 var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
	 s.type = 'text/javascript'; s.charset='UTF-8'; s.async = true;
	 s.src = ('https:' == window.location.protocol ? 'https' : 'http')  + '://share.pluso.ru/pluso-like.js';
	 var h=d[g]('head')[0] || d[g]('body')[0];
	 h.appendChild(s);
	})();</script>
	<div class="pluso" data-options="medium,round,multiline,horizontal,nocounter,theme=04" data-services="facebook,twitter,google,linkedin,vkontakte,odnoklassniki,livejournal,blogger" data-background="transparent" data-description="ПрофсоUX — главная питерская конференция о юзабилити, UX и создании цифровых продуктов, ориентированных на человека."></div> 
</div>