    <header id="header">
        <div class="container">
            <hgroup id="branding">
                <div class="offset4">
                    <h1 id="site-title" class="visible-desktop"><a class="hide-text" href="/">{{ site_title }}</a></h1>
                    <h2 id="site-description">{{ event.title }}</h2>
                    <p><time>{{ event.date }}</time>, {{ event.city }}, {{ event.place }}</p>
                </div>
            </hgroup>
        </div>
    </header>