    <header id="header">
        <div class="container">
            <hgroup id="branding" class="row">
                <div class="span3">
                    <p><a href="http://profsoux.ru/">« ProfsoUX</a></p>
                </div>
                <div class="offset3">
                    <h2 id="site-description">{{ flatpage.title }}</h2>
                    <p><time>19 мая 2013</time></p>
                </div>
            </hgroup>
        </div>
    </header>