    <header id="header">
        <div class="container">
            <hgroup id="branding">
                <div class="offset4">
                    <h1 id="site-title" class="visible-desktop"><a class="hide-text" href="/">{{ site_title }}</a></h1>
                    <h2 id="site-description">User Experience conference <br>&nbsp;</h2>
                    <p><time>May 18, 2013</time>, St. Petersburg, Russia</p>
                </div>
            </hgroup>
        </div>
    </header>